@API_HostAddress = https://localhost:5122/api
@SampleID = 1
@Attribute = recipient
@SampleEmail = ajmarrugos@gmail.com
@RecipientEmail = alberto.marrugo@unosquare.com

# Get all appointments
GET {{API_HostAddress}}/appointments
Accept: application/json
###

# Get appointment by ID
GET {{API_HostAddress}}/appointments/{{SampleID}}
Accept: application/json
###

# Get appointments by attribute query
GET {{API_HostAddress}}/appointments/{{Attribute}}/{{RecipientEmail}}
Accept: application/json
###

# Create a new appointment
POST {{API_HostAddress}}/appointments
Content-Type: application/json

{
    "Sender": "{{SampleEmail}}",
    "Recipient": "{{RecipientEmail}}",
    "Name": "Project Meeting",
    "Date": "2024-11-11",
    "Time": "13:30"
}
###

# Reschedule an appointment
PUT {{API_HostAddress}}/appointments/reschedule/{{SampleID}}
Content-Type: application/json

{
  "Sender": "{{SampleEmail}}",
  "Date": "2024-12-01",
  "Time": "14:00"
}
###

# Sign off an appointment (approve or cancel)
PUT {{API_HostAddress}}/appointments/signoff/{{SampleID}}
Content-Type: application/json

{
    "Status": "Approved"
}
###

# Delete an appointment
DELETE {{API_HostAddress}}/appointments/{{SampleID}}
Accept: application/json
###